apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: omicsdi-dev
  namespace: dev
spec:
  rules:
    - host: dev.omicsdi.org
      http:
        paths:
          - path: /*
            backend:
              serviceName: omicsdi-frontend
              servicePort: 8080
      